import { breadcrumbs, hero, linkButton } from '../templates/site.mjs';

const crumb = (label, path) => breadcrumbs([{ label: 'Inicio', path: '' }, { label, path }]);
const card = (title, text, path) => `<article class="card"><h2>${title}</h2><p>${text}</p>${linkButton(path, 'Abrir herramienta')}</article>`;
const field = (label, name, value, suffix) => `<label>${label}<span class="input-row"><input name="${name}" value="${value}" inputmode="decimal" required><span>${suffix}</span></span></label>`;
const error = '<div class="error" data-error role="alert" tabindex="-1" hidden></div>';

export const pages = [
  {
    path: '', h1: 'Marca el punto exacto antes de hacer el agujero', title: 'CuelgaMedido: calculadoras para colgar cuadros', description: 'Calcula altura de clavos, separaciones uniformes y posiciones de una cuadrícula de cuadros con vista previa.',
    schema: { '@context': 'https://schema.org', '@type': 'WebSite', name: 'CuelgaMedido', url: 'https://elvaropablo-oss.github.io/cuelga-medido/', inLanguage: 'es-ES' },
    content: `${hero('Del marco a la pared', 'Marca el punto exacto antes de hacer el agujero', 'Introduce medidas reales y obtén posiciones desde el suelo y el borde izquierdo. Puedes comprobar cada marca con cinta métrica antes de perforar.', `${linkButton('altura-clavo/', 'Calcular un cuadro')}${linkButton('cuadricula-cuadros/', 'Planificar una cuadrícula', true)}`)}
      <section class="section"><div class="section-heading"><p class="eyebrow">Tres problemas frecuentes</p><h2>Centro, separación y anclajes</h2></div><div class="card-grid">${card('Altura del clavo', 'Convierte altura visual, tamaño del marco y caída del herraje en una marca.', 'altura-clavo/')}${card('Repartir una fila', 'Centra una fila con hueco fijo o reparte el espacio por igual.', 'repartir-cuadros/')}${card('Cuadrícula completa', 'Calcula cada centro y cada altura de anclaje, con vista a escala.', 'cuadricula-cuadros/')}</div></section>
      <section class="section split"><div><p class="eyebrow">Mide el herraje</p><h2>El clavo no coincide con la parte superior</h2><p>La distancia entre el borde superior del marco y el punto real de apoyo cambia la marca. Cuelga el cable con tensión o mide la anilla tal como quedará montada.</p></div><aside class="sample"><p>Ejemplo</p><strong>Centro 145 cm + medio marco − caída</strong><p>Marco de 80 cm y caída de 10 cm: clavo a 175 cm del suelo.</p></aside></section>`
  },
  { path: 'herramientas', h1: 'Herramientas para colocar cuadros', title: 'Herramientas para colgar cuadros | CuelgaMedido', description: 'Calculadoras para clavos, filas y cuadrículas de marcos.', content: `${crumb('Herramientas', 'herramientas/')} ${hero('Directorio', 'Herramientas para colocar cuadros', 'Empieza midiendo el marco por fuera y el herraje con la tensión que tendrá en la pared.')}<section class="section card-grid">${card('Altura del clavo', 'Uno o dos puntos de anclaje centrados.', 'altura-clavo/')}${card('Repartir cuadros', 'Fila compacta o separación equilibrada.', 'repartir-cuadros/')}${card('Cuadrícula', 'Posiciones para varias filas y columnas.', 'cuadricula-cuadros/')}</section>` },
  {
    path: 'altura-clavo', tool: true, h1: 'Calcula dónde poner el clavo de un cuadro', title: 'Calcular altura del clavo para un cuadro | CuelgaMedido', description: 'Calcula altura y posición horizontal de uno o dos anclajes según el centro visual, el marco y el herraje.',
    content: `${crumb('Altura del clavo', 'altura-clavo/')} ${hero('Una marca comprobable', 'Calcula dónde poner el clavo de un cuadro', 'La posición se mide desde el suelo y desde el borde izquierdo del tramo de pared que quieras centrar.')}
      <section class="tool-layout"><form id="hook-form" class="tool-card"><fieldset><legend>Pared y marco</legend>${field('Ancho del tramo de pared', 'wallWidth', '300', 'cm')}${field('Ancho exterior del marco', 'frameWidth', '60', 'cm')}${field('Alto exterior del marco', 'frameHeight', '80', 'cm')}${field('Altura deseada del centro', 'centerHeight', '145', 'cm')}</fieldset><fieldset><legend>Anclaje</legend>${field('Distancia desde arriba al apoyo', 'hangerDrop', '10', 'cm')}${field('Separación entre dos anclajes', 'hookSeparation', '0', 'cm')}</fieldset>${error}<button class="button" type="submit">Calcular la marca</button></form><section id="hook-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="section prose"><h2>Cómo medir la caída</h2><p>Con una anilla, mide desde el borde superior hasta el punto que apoyará en el clavo. Con cable, tira del centro hacia arriba con la tensión real y mide hasta ese punto.</p><h2>Dos anclajes</h2><p>Escribe la distancia horizontal entre sus centros. La herramienta los coloca simétricamente respecto al centro del tramo de pared.</p></article>`
  },
  {
    path: 'repartir-cuadros', tool: true, h1: 'Reparte una fila de cuadros con precisión', title: 'Calculadora de separación entre cuadros | CuelgaMedido', description: 'Centra una fila de marcos iguales con separación fija o distribuye el mismo hueco entre cuadros y bordes.',
    content: `${crumb('Repartir cuadros', 'repartir-cuadros/')} ${hero('De izquierda a derecha', 'Reparte una fila de cuadros con precisión', 'Obtén el centro de cada marco medido desde el borde izquierdo del espacio disponible.')}
      <section class="tool-layout"><form id="row-form" class="tool-card"><fieldset><legend>Fila</legend>${field('Ancho disponible', 'availableWidth', '300', 'cm')}${field('Ancho de cada marco', 'frameWidth', '40', 'cm')}${field('Cantidad', 'count', '3', 'uds.')}${field('Separación deseada', 'gap', '10', 'cm')}</fieldset><label>Modo<select name="mode"><option value="compact">Separación fija y fila centrada</option><option value="balanced">Mismo hueco en bordes e interiores</option></select></label>${error}<button class="button" type="submit">Calcular posiciones</button></form><section id="row-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section>
      <article class="section prose"><h2>Qué marca debes transferir</h2><p>Las posiciones son centros horizontales de marco. Para convertirlas en clavos necesitas conocer la altura elegida y la caída del herraje.</p><h2>Marcos diferentes</h2><p>Esta versión trabaja con marcos iguales. Para una composición desigual, coloca plantillas de papel y decide visualmente antes de medir anclajes.</p></article>`
  },
  {
    path: 'cuadricula-cuadros', tool: true, h1: 'Planifica una cuadrícula de cuadros', title: 'Calculadora de cuadrícula para cuadros | CuelgaMedido', description: 'Calcula el tamaño del conjunto, los centros y la altura de cada anclaje para una cuadrícula de marcos iguales.',
    content: `${crumb('Cuadrícula', 'cuadricula-cuadros/')} ${hero('Filas alineadas', 'Planifica una cuadrícula de cuadros', 'La vista previa conserva la proporción de la pared. La tabla da medidas para cada marco desde el suelo y la izquierda.')}
      <section class="tool-layout"><form id="grid-form" class="tool-card"><fieldset><legend>Pared</legend>${field('Ancho', 'wallWidth', '300', 'cm')}${field('Alto', 'wallHeight', '240', 'cm')}${field('Altura del centro del conjunto', 'centerHeight', '140', 'cm')}</fieldset><fieldset><legend>Marcos</legend>${field('Ancho de cada marco', 'frameWidth', '40', 'cm')}${field('Alto de cada marco', 'frameHeight', '50', 'cm')}${field('Columnas', 'columns', '3', 'uds.')}${field('Filas', 'rows', '2', 'uds.')}${field('Hueco horizontal', 'gapX', '10', 'cm')}${field('Hueco vertical', 'gapY', '10', 'cm')}${field('Caída del anclaje', 'hangerDrop', '5', 'cm')}</fieldset>${error}<button class="button" type="submit">Crear plano de marcas</button></form><section id="grid-result" class="result" tabindex="-1" aria-live="polite" hidden></section></section><section id="wall-preview" class="wall-preview" aria-label="Vista previa de la pared" hidden></section>
      <article class="section prose"><h2>Orden de medición</h2><p>Marca primero el centro del conjunto. Después transfiere los centros horizontales y, por último, las alturas de anclaje. Comprueba diagonales y usa un nivel antes de perforar.</p></article>`
  },
  { path: 'guias/medir-anclaje', h1: 'Cómo medir el anclaje de un cuadro', title: 'Cómo medir cable, anilla y ganchos de cuadros | CuelgaMedido', description: 'Mide la caída real del sistema de colgado y evita errores al trasladar la posición a la pared.', content: `${crumb('Medir el anclaje', 'guias/medir-anclaje/')} ${hero('El dato que suele faltar', 'Cómo medir el anclaje de un cuadro', 'Dos marcos iguales pueden necesitar clavos a distinta altura si su herraje cambia.')}<article class="section prose"><h2>Anilla o soporte rígido</h2><p>Mide verticalmente desde el borde superior del marco hasta el punto interior donde descansará el gancho.</p><h2>Cable</h2><p>Apoya el marco boca abajo, tira del cable hacia arriba por el centro hasta tensarlo y mide desde ese punto hasta el borde superior. No uses la caída del cable suelto.</p><h2>Dos puntos</h2><p>Mide entre centros de anillas. Comprueba que están a la misma distancia del borde superior; si no, calcula cada altura por separado.</p>${linkButton('altura-clavo/', 'Calcular la marca')}</article>` },
  { path: 'guias/plantillas-papel', h1: 'Prueba la composición con plantillas de papel', title: 'Plantillas de papel para colocar cuadros | CuelgaMedido', description: 'Comprueba tamaño, separación y altura visual antes de perforar la pared.', content: `${crumb('Plantillas de papel', 'guias/plantillas-papel/')} ${hero('Ensaya sin agujeros', 'Prueba la composición con plantillas de papel', 'La matemática alinea; la plantilla permite juzgar cómo se ve en la habitación.')}<article class="section prose"><h2>Traza cada marco</h2><p>Corta papel del tamaño exterior, escribe su número y marca la posición del anclaje dentro de la plantilla.</p><h2>Coloca y revisa</h2><p>Usa cinta que no dañe la pintura. Mira el conjunto desde la entrada y desde la zona donde se usa la habitación. Ajusta la composición antes de copiar los puntos de anclaje.</p></article>` },
  { path: 'metodologia', h1: 'Fórmulas y límites de CuelgaMedido', title: 'Metodología | CuelgaMedido', description: 'Consulta las fórmulas para alturas, filas y cuadrículas de cuadros.', content: `${crumb('Metodología', 'metodologia/')} ${hero('Geometría visible', 'Fórmulas y límites de CuelgaMedido', 'Todos los resultados usan rectángulos alineados y distancias desde dos referencias físicas.')}<article class="section prose"><h2>Altura del anclaje</h2><p>Altura = centro visual + alto del marco ÷ 2 − caída del herraje.</p><h2>Fila compacta</h2><p>Ancho = cantidad × ancho de marco + (cantidad − 1) × separación. El sobrante se divide por dos para centrar la fila.</p><h2>Distribución equilibrada</h2><p>Hueco = (ancho disponible − ancho total de marcos) ÷ (cantidad + 1), de modo que bordes e interiores coincidan.</p><h2>Cuadrícula</h2><p>El conjunto se centra en el ancho de pared y en la altura indicada. Las posiciones se dan al centro de cada marco; la caída convierte cada centro en altura de anclaje.</p></article>` },
  { path: 'sobre', h1: 'Sobre CuelgaMedido', title: 'Sobre el proyecto | CuelgaMedido', description: 'Propósito y alcance de CuelgaMedido.', content: `${crumb('Sobre', 'sobre/')} ${hero('Antes de perforar', 'Sobre CuelgaMedido', 'El proyecto ayuda a trasladar una composición sencilla a marcas medibles.')}<article class="section prose"><h2>Alcance</h2><p>La V1 cubre un marco, filas y cuadrículas de marcos iguales. No evalúa el peso soportado, el material de la pared ni el tipo de taco.</p><h2>Responsabilidad física</h2><p>Elige fijaciones adecuadas al peso y a la pared. Si existen conducciones ocultas o dudas estructurales, consulta a un profesional.</p></article>` },
  { path: 'privacidad', h1: 'Privacidad', title: 'Privacidad | CuelgaMedido', description: 'Información sobre privacidad de CuelgaMedido.', content: `${crumb('Privacidad', 'privacidad/')} ${hero('Cálculos locales', 'Privacidad', 'Las medidas se procesan en este navegador.')}<article class="section prose"><h2>Datos introducidos</h2><p>Las dimensiones no se suben a un servidor. El último cálculo puede guardarse localmente en este navegador.</p><h2>Analítica</h2><p>Esta versión no instala Google Analytics ni servicios publicitarios.</p></article>` },
  { path: '404', output: '404.html', noindex: true, h1: 'Página no encontrada', title: 'Página no encontrada | CuelgaMedido', description: 'La página solicitada no existe.', content: `${hero('Error 404', 'Página no encontrada', 'La dirección puede contener un error o haber cambiado.', linkButton('', 'Volver al inicio'))}` }
];
